### ISSUE TITLE
error in process filter: Wrong type argument: plistp, "{}"

### ISSUE THREAD

**Issue by RadSpaceEd** [Leathong/openscad-LSP#19]
Every time I use completion-at-point there's a significant slow down, and Emacs echoes out this error. The completion works sometimes after that.

- Emacs version 30.0.50
- LSP client is Eglot
- Completion engine is Corfu & Vertico

Relevant configuration:
```
(use-package eglot
  :mode ("\\.scad$" "\\.c$" "\\.js$" "\\.html$" "\\.css$")
  :config (add-to-list 'eglot-server-programs
		       '(scad-mode . ("openscad-lsp" "--stdio")))
  :hook (scad-mode . eglot-ensure)
  )
```
The included Eglot LSPs work fine.

**Comment by RadSpaceEd** [comment]
Oh, and I may also add that I use [scad-mode](https://github.com/openscad/emacs-scad-mode) for the syntax highlighting.

**Comment by RadSpaceEd** [comment]
Just now noticed the EGLOT message buffer. Here's what happened when I reproduced the bug:
```
[internal] (id:5) Mon Jun  5 21:36:59 2023:
(:timed-out :textDocument/hover :id 5 :params
	    (:textDocument
	     (:uri "file:///home/zezin/dox/notes/projects/3dprinter/assembly.scad")
	     :position
	     (:line 117 :character 3)))
[client-request] (id:7) Mon Jun  5 21:37:00 2023:
(:jsonrpc "2.0" :id 7 :method "textDocument/hover" :params
	  (:textDocument
	   (:uri "file:///home/zezin/dox/notes/projects/3dprinter/assembly.scad")
	   :position
	   (:line 117 :character 3)))
[server-reply] (id:7) Mon Jun  5 21:37:00 2023:
(:jsonrpc "2.0" :id 7 :result "{}")
```

I suspect that this `result "{}"` that is causing problems.

**Comment by RadSpaceEd** [comment]
Just noticed that I actually didn't capture the completion request. But when Emacs finished the lockup and showed the completion candidates the Eglot message buffer clears up, not giving me the opportunity to copy it.

**Comment by Leathong** [comment]
Which version do you have installed? If is not newest version, you can update to 1.2.4 and try again.

**Comment by Leathong** [comment]
You can use the command "openscad-lsp -V" to view the version.

**Comment by RadSpaceEd** [comment]
It's the latest version.

**Comment by kmontag** [comment]
Just reporting that I'm seeing the same issue with version 1.2.4 (I believe it was happening with 1.2.3 as well).

**Comment by Lenbok** [comment]
I have been using this with emacs `lsp-mode` fine, but I guess it is more lenient than `eglot` in some way. (A few weeks ago I had a quick attempt to try `eglot` for the first time, with this server, and think I hit this issue too, but hadn't revisited since).

**Comment by Leathong** [comment]
> 

Maybe I should response a {"value": ""} instead of {}, I will try it.

**Comment by Leathong** [comment]
@Lenbok @kmontag @RadSpaceEd You can try this fix https://github.com/Leathong/openscad-LSP/commit/b6d5a3e6534516731874a7bc11d4b6cc0b1a44f5, I will update it in cargo if it works.

**Comment by RadSpaceEd** [comment]
Still the same behaviour, but now the error message has changed to `error in process filter: Wrong type argument: plistp, "null" [10 times]`

**Comment by Leathong** [comment]
@RadSpaceEd replace "null" with null, I believe it will work.

**Comment by RadSpaceEd** [comment]
@Leathong It worked without errors now. There's still a pretty significant slowdown between running `completion-at-point` and getting the completion candidates,  but now it works. 

Thank you very very much!

**Comment by RadSpaceEd** [comment]
Here's a video as evidence of the slow down... I don't know if this should be a different issue at this point.

[untitled.webm](https://github.com/Leathong/openscad-LSP/assets/58449046/33f919b3-61e1-4504-a3c3-865e9e40ca18)

**Comment by RadSpaceEd** [comment]
I just tried the completion on a blank file and it was way faster. I think the problem is that the library I imported [NopSCADlib](https://github.com/nophead/NopSCADlib) has a bunch of functions, so there's way more code to look through to offer the completion candidates. As soon as include the library things slow down again. 

Is there anything I can do to optimize this process?

**Comment by Leathong** [comment]
https://github.com/Leathong/openscad-LSP/blob/3278d8ca58a3f9bfcaf0a85f1013e10a6ae23c23/src/server/code_helper.rs#L45 Current search depth is 5, if it is too slow , you can try reduce it.

**Comment by Leathong** [comment]
NopSCADlib  has a lot of cross-references, and including this library will result in a large number of symbols.

**Comment by Leathong** [comment]
I changed it to 3 https://github.com/Leathong/openscad-LSP/commit/dc1283df080b981f8da620744b0fb53b22f2eb84

**Comment by RadSpaceEd** [comment]
@Leathong it improved slightly, but now I know what to edit. Thanks!
