### ISSUE TITLE
Allow specifying port

### ISSUE THREAD

**Issue by Lenbok** [Leathong/openscad-LSP#2]
It appears that the port is hardcoded to 3245, which would prevent running multiple instances on the same machine. Most other tcp servers allow the port to be specified, e.g. via command line flag `--port`. Can this be added?

**Comment by Lenbok** [comment]
BTW, because of the above I couldn't yet work out how to connect to emacs lsp-mode, as the examples I could see wanted to dictate the port. 

However, I simply swapped the main of your server implementation in `main.rs` to use the stdio-based connection that dzhu's implementation used, and I can now use your server inside emacs lsp-mode.  Why did you choose to implement tcp over a stdio based connection?

**Comment by Leathong** [comment]
> It appears that the port is hardcoded to 3245, which would prevent running multiple instances on the same machine. Most other tcp servers allow the port to be specified, e.g. via command line flag `--port`. Can this be added?

Sure, it's a nice feature. I will add it in the next few days.

**Comment by Leathong** [comment]
> 



> 

It may be need to output some information via stdio in the future.

**Comment by Leathong** [comment]
> BTW, because of the above I couldn't yet work out how to connect to emacs lsp-mode, as the examples I could see wanted to dictate the port.
> 
> However, I simply swapped the main of your server implementation in `main.rs` to use the stdio-based connection that dzhu's implementation used, and I can now use your server inside emacs lsp-mode. Why did you choose to implement tcp over a stdio based connection?

It may be need to output some information via stdio in the future.

**Comment by Leathong** [comment]
done

**Comment by Lenbok** [comment]
Thanks, the tcp connection method is working for me now.
