### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by simurgh9** [Leathong/openscad-LSP#25]
I am trying to use this server but am running into an issue with using it on Emacs.  My version is `1.0.0` since I just downloaded the Mac binary from the releases.  Is there anyway a new release can be made since I do not want to download the rust toolchain?

**Comment by Leathong** [comment]
@simurgh9 I will upload a new release binary this weekend.

**Comment by simurgh9** [comment]
_twiddles thumbs_

**Comment by Leathong** [comment]
@simurgh9 Sorry, I'm busy as hell for the past weeks, I have uploaded the new release.
