### ISSUE TITLE
How to use formatter?

### ISSUE THREAD

**Issue by eliliam** [Leathong/openscad-LSP#29]
After installing this extension and seeing it required clang-format, I went ahead and installed clang-format manually and configured VS Code with the executable path, however no matter what I try I can't seem to get VS Code to format my scad file. When I try running "Format Document" it says that there are no formatters available for openscad documents and then directs me to your extension as the only one that can(which is already installed). Am I missing something here? I don't see any way to actually format the scad document in VS Code or even via the command line even after installing openscad-lsp via cargo.

**Comment by Leathong** [comment]
https://github.com/Leathong/openscad-support-vscode
